# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UMate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UMate
pod 'Elliotable'
pod 'Cosmos'
pod 'DropDown'
pod 'BEMCheckBox'
pod 'KeychainSwift', '~> 19.0'
pod 'Loaf', :git => 'https://github.com/hyeffie/Loaf.git'
pod 'AZSClient'
pod 'RxSwift'
pod 'RxCocoa'
pod 'NSObject+Rx'
end
